### PR TITLE
We need to send preVerificationGas to paymaster api as well.

### PR DESCRIPTION
**Pull request by plusminushalf**

### CODE REVIEW

**Comment by drortirosh** [comment]
that is very tricky: preVerificationGas should include entire callData. the paymaster data filled in is part of it. what we can do is fill it in assuming no paymasterdata, and re-calculate it afterwards (or, just adding the cost of paymasterAndData)

**Comment by plusminushalf** [comment]
Oh yes I see, so the issue is that VerifyingPaymaster needs everything except for signature to create a valid signature for a userOperation. But preVerificationGas needs the entire callData. Either we remove preVerificationGas from the verifyingPaymaster or find a way to add the cost of paymasterAndData later.

**Comment by plusminushalf** [comment]
How are we currently adding the cost of signature to preVerificationGas? I have not explored that code.

**Comment by drortirosh** [comment]
Currently the calculation assume a default signature of 65 non zero bytes
See here
https://github.com/eth-infinitism/bundler/blob/9b0c62d5a0229a5f4a2e432ac5e4d006ebbc3c49/packages/sdk/src/calcPreVerificationGas.ts#L60

This default is used only if the given UserOp doesn't contain a signature

**Comment by drortirosh** [comment]
As a verifying paymaster, I wouldn't ignore the preVG. A user might put a
huge value, and you, as a paymaster would pay for it..
Need a way to estimate it, eg by putting some value into the
paymasterAndData when calculating it.
I need to think what is the best way to add this into the api.
(Probably by adding "paymasterAndData size" parameter.
Maybe we should also add signatureSize, and default that to 65)

**Comment by plusminushalf** [comment]
Can we add a function `getSignatureLength` to Wallet's implementation. The function can be of the definition:

```solidity
function getSignatureLength(UserOperation calldata userOp) public view  returns(uint256) {
}
```

Similarily we can add a function `getPaymasterAndDatalength` to paymaster implementation.  The function can be of the definition:

```solidity
function getPaymasterAndDatalength(UserOperation calldata userOp) public view  returns(uint256) {
}
```

The functions can then be called before calling `getPaymasterAndData` & `signUserOp`. Once we have the expected length we add it to the `callData` and continue as we normally do.

**Review by drortirosh — APPROVED** [review]

**Pull request closed without merging**
